version: 0.2

phases:
  install:
    commands:
      - echo "Extracting Hugo binary..."
      - tar -xzf hugo_extended_0.121.0_linux-amd64.tar.gz
      - chmod +x hugo
      - ./hugo version
  build:
    commands:
      - echo "Building Hugo site..."
      - cd my-hugo-site
      - ../hugo --minify
artifacts:
  base-directory: my-hugo-site/public
  files:
    - '**/*'
