baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'JudgeMyLawyer⚖️'
theme = 'PaperMod'

[params]
  [params.homeInfoParams]
    Title = "⚖️ JudgeMyLawyer"
    Content = "Hello Professor! This is proof that CI/CD is working. This text was pushed to GitHub and automatically deployed to AWS S3 via CodePipeline."
